### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/eeg-qc-dash#1]
- [x] Redo table
- [x] Index column?
- [x] Last saved status in one line
- [x] Loading status
- [x] Move table selector column next to date
- [x] Various instruction messages
- [x] Logo, Zenodo ID
- [x] Non-root URL viewing
- [x] Filter boxes width
- [x] AVG images must be on the top of the views

---

- [x] Shrink images
- [x] Devise a naming strategy for average subject ID and session ID
- [x] Vue like average anchor frame stuck to top
- [x] -9 for missing instead of 0
- [x] Annotate scores 1-4
- [x] Comment box under `QC Score` column
- [x] Correct Spero's naming mistake of CAavg
- [x] Show site average in addition to grand average only when a site is filtered
- [x] Fit table cells to content-width
- [x] Save average row scores/comments
- [x] Put save button to the end/keep always visible
- [x] Scroll up behavior is a little annoying because of content above stuck table
- [x] Put introduction within `html.Details`
- [x] `GRANDavg` string causes column width mismatch, red thick border may have contributed to this problem too

---
- [x] Dropdown menu for sort order
- [x] Default start date should be T-1 month
  Default dates are still not populating right
  Set through a callback function, now they should be reliably set.
- [x] Show all six images by default
- [x] Hook up EEG tech code filter 
- [x] Generate separate Nginx password for team members
- [x] Move `.scores.pkl` to `/data/predict/kcho/flow_test/spero`
- [x] Remove debugger from production instance
- [x] Label for filters e.g. earliest date, latest date

**Comment by tashrifbillah** [comment]
Non-root URL works for only:

```nginx
location /eegqc/ {
    proxy_pass http://127.0.0.1:8051;
}
```

```bash
export DASH_URL_BASE_PATHNAME=/eegqc/
```

and, surprisingly, if each image source is prepended with `/eegqc/`: 
>/eegqc/Pronet/PHOENIX/PROTECTED/PronetLA/processed/LAavg/eeg/ses-00000000/Figures/LAavg_00000000_QCresponseAccuracy.png

**Comment by tashrifbillah** [comment]
Current solution of `width=100` is not visually pleasant for one image. That one image expands across the whole page!

**Comment by tashrifbillah** [comment]
Dropdown menu for sort order:
* Latest first
Descending order of just `{ses}` string
* Earliest first
Ascending order of just `{ses}` string
* Alphabetical
ascending order of `f'{sub}_eeg_{ses}'` string
