### ISSUE TITLE
For the time being TODO

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/eeg-qc-dash#18]
- [x] Put averages under collapsible layout
- [x] Remove default date filter
- [x] Remove complex logic for initial rendering with clear instruction to press Filter
- [x] Insert hyperlink of run sheet txt/pdf under this block, within the cell:
https://github.com/AMP-SCZ/eeg-qc-dash/blob/b618b5368073092275ba67ef8b919aeb6def6da9/app.py#L394-L401

(separation of run sheets by date would be hard because API pulls them only by visit e.g. baseline_arm_1, month_2_arm_1. We should be able to pull all run sheets of a record together though. Maybe that is what we want to do. And then the user would be responsible to scroll through the PDF to find the relevant one.)

Superseded by https://github.com/AMP-SCZ/eeg-qc-dash/issues/20
