### ISSUE TITLE
New TODO

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/eeg-qc-dash#8]
- [x] Need a method for dynamically loading the types of QC images
- [x] Also need one for telling `app.py` what should be rendered dynamically
- [x] Generate static site list of all sites
- [x] Show bigger view of each image on hover
(Amazon like cool feature might not be possible but we can have a hyperlink at the bottom to take clicker to new tab of original images size)
That cool feature may not be implemented, but it is achieved differently via https://github.com/AMP-SCZ/eeg-qc-dash/commit/0bfb5aa88f6abd6dde4fed9a4b2b31870595b7f1
- [ ] EEG run sheet requires quality checking colors just like MRI QC row

![image](https://user-images.githubusercontent.com/35086881/168674067-26582e20-a174-424e-a1eb-11ece664e434.png)

Primary fields to quality check would be `chreeg_primaryperson` and `chreeg_interview_date`.

- [ ] Prepend `__file__` to https://github.com/AMP-SCZ/eeg-qc-dash/blob/1603cf370b0b0d5f31606efd198e6e528b834078/app.py#L48-L49

**Comment by tashrifbillah** [comment]
cc @speroNCIRE

**Comment by tashrifbillah** [comment]
The remaining two would probably never be done, so closing this issue.

**Comment by speroNCIRE** [comment]
One of the items in the EEGquick dpdash form was a runsheet-derived QC scalar.  Is that in the spirit of your 1st unchecked box?  I'd maybe check that one off too.

**Comment by tashrifbillah** [comment]
> Is that in the spirit of your 1st unchecked box?

Thank you Spero. I realize that you actually have generated the measure I have always pondered how to generate. I shall use that.
